/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkoutDto } from '../../models/workout-dto';

export interface List$Params {
  muscleGroup?: 'TOTAL_BODY' | 'LEGS' | 'GLUTES' | 'ABS' | 'CORE' | 'CHEST' | 'BACK' | 'ARMS';
  authorId?: number;
  minDuration?: number;
  maxDuration?: number;
}

export function list(http: HttpClient, rootUrl: string, params?: List$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<WorkoutDto>>> {
  const rb = new RequestBuilder(rootUrl, list.PATH, 'get');
  if (params) {
    rb.query('muscleGroup', params.muscleGroup, {});
    rb.query('authorId', params.authorId, {});
    rb.query('minDuration', params.minDuration, {});
    rb.query('maxDuration', params.maxDuration, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<WorkoutDto>>;
    })
  );
}

list.PATH = '/api/workouts';
