/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProgramCycleDto } from '../../models/program-cycle-dto';

export interface List2$Params {
  programId: number;
}

export function list2(http: HttpClient, rootUrl: string, params: List2$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProgramCycleDto>>> {
  const rb = new RequestBuilder(rootUrl, list2.PATH, 'get');
  if (params) {
    rb.path('programId', params.programId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ProgramCycleDto>>;
    })
  );
}

list2.PATH = '/api/programs/{programId}/cycles';
