/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PlannedSessionDto } from '../../models/planned-session-dto';

export interface Incomplete$Params {
  id: number;
}

export function incomplete(http: HttpClient, rootUrl: string, params: Incomplete$Params, context?: HttpContext): Observable<StrictHttpResponse<PlannedSessionDto>> {
  const rb = new RequestBuilder(rootUrl, incomplete.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PlannedSessionDto>;
    })
  );
}

incomplete.PATH = '/api/planned-sessions/{id}/incomplete';
