/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PlannedSessionDto } from '../../models/planned-session-dto';
import { PlannedSessionRescheduleRequest } from '../../models/planned-session-reschedule-request';

export interface Reschedule$Params {
  id: number;
      body: PlannedSessionRescheduleRequest
}

export function reschedule(http: HttpClient, rootUrl: string, params: Reschedule$Params, context?: HttpContext): Observable<StrictHttpResponse<PlannedSessionDto>> {
  const rb = new RequestBuilder(rootUrl, reschedule.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PlannedSessionDto>;
    })
  );
}

reschedule.PATH = '/api/planned-sessions/{id}/reschedule';
