/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AuthorDto } from './models/author-dto';
export type { AuthorRequest } from './models/author-request';
export type { BodyMeasurementDto } from './models/body-measurement-dto';
export type { CalendarDayDto } from './models/calendar-day-dto';
export type { GarminImportResultDto } from './models/garmin-import-result-dto';
export type { PlannedSessionDto } from './models/planned-session-dto';
export type { PlannedSessionRequest } from './models/planned-session-request';
export type { PlannedSessionRescheduleRequest } from './models/planned-session-reschedule-request';
export type { ProgramCycleDto } from './models/program-cycle-dto';
export type { ProgramCycleRequest } from './models/program-cycle-request';
export type { ProgramDayDto } from './models/program-day-dto';
export type { ProgramDayRequest } from './models/program-day-request';
export type { ProgramDto } from './models/program-dto';
export type { ProgramRequest } from './models/program-request';
export type { ProgramSummaryDto } from './models/program-summary-dto';
export type { ProgramWorkoutDto } from './models/program-workout-dto';
export type { ProgramWorkoutRequest } from './models/program-workout-request';
export type { SessionDto } from './models/session-dto';
export type { WorkoutDto } from './models/workout-dto';
export type { WorkoutRequest } from './models/workout-request';
export type { WorkoutSummaryDto } from './models/workout-summary-dto';
