spring:
  application:
    name: bloom-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:bloom}
    username: ${POSTGRES_USER:bloom}
    password: ${POSTGRES_PASSWORD:bloom}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
