/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GarminImportResultDto } from '../../models/garmin-import-result-dto';

export interface ImportCsv$Params {
      body?: {
'file': Blob;
}
}

export function importCsv(http: HttpClient, rootUrl: string, params?: ImportCsv$Params, context?: HttpContext): Observable<StrictHttpResponse<GarminImportResultDto>> {
  const rb = new RequestBuilder(rootUrl, importCsv.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GarminImportResultDto>;
    })
  );
}

importCsv.PATH = '/api/sessions/import';
