/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SessionDto } from '../../models/session-dto';

export interface List6$Params {
  from?: string;
  to?: string;
}

export function list6(http: HttpClient, rootUrl: string, params?: List6$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SessionDto>>> {
  const rb = new RequestBuilder(rootUrl, list6.PATH, 'get');
  if (params) {
    rb.query('from', params.from, {});
    rb.query('to', params.to, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SessionDto>>;
    })
  );
}

list6.PATH = '/api/sessions';
