/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CalendarDayDto } from '../../models/calendar-day-dto';

export interface List7$Params {
  from?: string;
  to?: string;
}

export function list7(http: HttpClient, rootUrl: string, params?: List7$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CalendarDayDto>>> {
  const rb = new RequestBuilder(rootUrl, list7.PATH, 'get');
  if (params) {
    rb.query('from', params.from, {});
    rb.query('to', params.to, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CalendarDayDto>>;
    })
  );
}

list7.PATH = '/api/calendar';
