/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BodyMeasurementDto } from '../../models/body-measurement-dto';

export interface List4$Params {
  from?: string;
  to?: string;
}

export function list4(http: HttpClient, rootUrl: string, params?: List4$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<BodyMeasurementDto>>> {
  const rb = new RequestBuilder(rootUrl, list4.PATH, 'get');
  if (params) {
    rb.query('from', params.from, {});
    rb.query('to', params.to, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<BodyMeasurementDto>>;
    })
  );
}

list4.PATH = '/api/body-measurements';
