/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BodyMeasurementDto {
  armLeft?: number;
  armRight?: number;
  bmi?: number;
  bodyFatPct?: number;
  bonesPct?: number;
  calfLeft?: number;
  calfRight?: number;
  chest?: number;
  date: string;
  forearmLeft?: number;
  forearmRight?: number;
  hips?: number;
  id?: number;
  muscleMass?: number;
  stomach?: number;
  thighLeft?: number;
  thighRight?: number;
  waist?: number;
  waterPct?: number;
  weight?: number;
}
