/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PlannedSessionDto } from '../models/planned-session-dto';
import { SessionDto } from '../models/session-dto';
export interface CalendarDayDto {
  actual?: Array<SessionDto>;
  date?: string;
  planned?: Array<PlannedSessionDto>;
}
