/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WorkoutSummaryDto } from '../models/workout-summary-dto';
export interface PlannedSessionDto {
  completed?: boolean;
  date?: string;
  id?: number;
  programCycleId?: number;
  programWorkoutId?: number;
  workout?: WorkoutSummaryDto;
}
