/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProgramDayDto } from '../models/program-day-dto';
export interface ProgramDto {
  days?: Array<ProgramDayDto>;
  description?: string;
  id?: number;
  name?: string;
}
