/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProgramWorkoutDto } from '../models/program-workout-dto';
export interface ProgramDayDto {
  dayNumber?: number;
  id?: number;
  workouts?: Array<ProgramWorkoutDto>;
}
