/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProgramDayRequest } from '../models/program-day-request';
export interface ProgramRequest {
  days?: Array<ProgramDayRequest>;
  description?: string;
  name: string;
}
