/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProgramWorkoutRequest } from '../models/program-workout-request';
export interface ProgramDayRequest {
  workouts?: Array<ProgramWorkoutRequest>;
}
