/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProgramCycleDto {
  endDate?: string;
  id?: number;
  programId?: number;
  programName?: string;
  startDate?: string;
}
