/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WorkoutSummaryDto } from '../models/workout-summary-dto';
export interface ProgramWorkoutDto {
  id?: number;
  order?: number;
  workout?: WorkoutSummaryDto;
}
