/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SessionDto {
  avgHeartRate?: number;
  calories?: number;
  date?: string;
  distance?: number;
  durationSeconds?: number;
  id?: number;
  maxHeartRate?: number;
  title?: string;
  type?: 'YOGA' | 'STRENGTH_TRAINING' | 'POOL_SWIMMING' | 'WALKING';
}
