/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AuthorDto } from '../models/author-dto';
export interface WorkoutDto {
  author?: AuthorDto;
  durationMinutes?: number;
  id?: number;
  muscleGroups?: Array<'TOTAL_BODY' | 'LEGS' | 'GLUTES' | 'ABS' | 'CORE' | 'CHEST' | 'BACK' | 'ARMS'>;
  name?: string;
  notes?: string;
  youtubeUrl?: string;
}
