/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WorkoutRequest {
  authorId: number;
  durationMinutes?: number;
  muscleGroups?: Array<'TOTAL_BODY' | 'LEGS' | 'GLUTES' | 'ABS' | 'CORE' | 'CHEST' | 'BACK' | 'ARMS'>;
  name: string;
  notes?: string;
  youtubeUrl?: string;
}
